name: dylib
description: A set of helpers that help resolving names and paths of dynamic libraries.
version: 0.1.0-nullsafety.0
homepage: https://github.com/jpnurmi/dart_dylib
repository: https://github.com/jpnurmi/dart_dylib
issue_tracker: https://github.com/jpnurmi/dart_dylib/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
