name: dylib
description: A set of helpers that help resolving names and paths of dynamic libraries.
version: 0.3.1
homepage: https://github.com/jpnurmi/dart_dylib
repository: https://github.com/jpnurmi/dart_dylib
issue_tracker: https://github.com/jpnurmi/dart_dylib/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  platform: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
  test_coverage: ^0.5.0

dependency_overrides:
  args: ^2.0.0
  coverage: ^1.0.1
  glob: ^2.0.0
